# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './designer/practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from aqt.qt import *


class Ui_Practice(object):
    def setupUi(self, Practice):
        Practice.setObjectName("Practice")
        Practice.resize(856, 620)
        font = QFont()
        font.setPointSize(8)
        Practice.setFont(font)
        self.gridLayout = QGridLayout(Practice)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QWidget(Practice)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 15, 1)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelLeft = QLabel(Practice)
        self.labelLeft.setObjectName("labelLeft")
        self.horizontalLayout.addWidget(self.labelLeft)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelRight = QLabel(Practice)
        self.labelRight.setAlignment(Qt.AlignmentFlag.AlignRight.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.labelRight.setObjectName("labelRight")
        self.horizontalLayout.addWidget(self.labelRight)
        self.toolButton = QToolButton(Practice)
        font = QFont()
        font.setPointSize(8)
        self.toolButton.setFont(font)
        self.toolButton.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(Qt.ArrowType.DownArrow)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalWidget = QWidget(Practice)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.wrongArea = QHBoxLayout(self.horizontalWidget)
        self.wrongArea.setObjectName("wrongArea")
        self.label = QLabel(self.horizontalWidget)
        self.label.setObjectName("label")
        self.wrongArea.addWidget(self.label)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.wrongArea.addItem(spacerItem1)
        self.cardsButton = QPushButton(self.horizontalWidget)
        self.cardsButton.setObjectName("cardsButton")
        self.wrongArea.addWidget(self.cardsButton)
        self.pushButton = QPushButton(self.horizontalWidget)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.wrongArea.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.horizontalWidget, 16, 0, 1, 1)

        self.retranslateUi(Practice)
        QMetaObject.connectSlotsByName(Practice)

    def retranslateUi(self, Practice):
        _translate = QCoreApplication.translate
        Practice.setWindowTitle(_translate("Practice", "Form"))
        self.labelLeft.setText(_translate("Practice", "TextLabel"))
        self.labelRight.setText(_translate("Practice", "TextLabel"))
        self.toolButton.setText(_translate("Practice", "..."))
        self.label.setText(_translate("Practice", "Incorrect!"))
        self.cardsButton.setText(_translate("Practice", "Card(s)"))
        self.pushButton.setText(_translate("Practice", "OK"))
