# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Practice(object):
    def setupUi(self, Practice):
        Practice.setObjectName("Practice")
        Practice.resize(856, 620)
        font = QtGui.QFont()
        font.setPointSize(8)
        Practice.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Practice)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Practice)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 15, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelLeft = QtWidgets.QLabel(Practice)
        self.labelLeft.setObjectName("labelLeft")
        self.horizontalLayout.addWidget(self.labelLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelRight = QtWidgets.QLabel(Practice)
        self.labelRight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRight.setObjectName("labelRight")
        self.horizontalLayout.addWidget(self.labelRight)
        self.toolButton = QtWidgets.QToolButton(Practice)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toolButton.setFont(font)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalWidget = QtWidgets.QWidget(Practice)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.wrongArea = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.wrongArea.setObjectName("wrongArea")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        self.label.setObjectName("label")
        self.wrongArea.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.wrongArea.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.wrongArea.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.horizontalWidget, 16, 0, 1, 1)

        self.retranslateUi(Practice)
        QtCore.QMetaObject.connectSlotsByName(Practice)

    def retranslateUi(self, Practice):
        _translate = QtCore.QCoreApplication.translate
        Practice.setWindowTitle(_translate("Practice", "Form"))
        self.labelLeft.setText(_translate("Practice", "TextLabel"))
        self.labelRight.setText(_translate("Practice", "TextLabel"))
        self.toolButton.setText(_translate("Practice", "..."))
        self.label.setText(_translate("Practice", "Incorrect!"))
        self.pushButton.setText(_translate("Practice", "OK"))
