# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'summary.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Summary(object):
    def setupUi(self, Summary):
        Summary.setObjectName("Summary")
        Summary.resize(372, 289)
        self.gridLayout = QtWidgets.QGridLayout(Summary)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Summary)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Summary)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Summary)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.accuracyLabel = QtWidgets.QLabel(Summary)
        self.accuracyLabel.setObjectName("accuracyLabel")
        self.gridLayout.addWidget(self.accuracyLabel, 1, 1, 1, 1)
        self.correctLabel = QtWidgets.QLabel(Summary)
        self.correctLabel.setObjectName("correctLabel")
        self.gridLayout.addWidget(self.correctLabel, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Summary)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cardsLabel = QtWidgets.QLabel(Summary)
        self.cardsLabel.setObjectName("cardsLabel")
        self.gridLayout.addWidget(self.cardsLabel, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Summary)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.timeLabel = QtWidgets.QLabel(Summary)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 3, 1, 1, 1)

        self.retranslateUi(Summary)
        self.buttonBox.accepted.connect(Summary.accept) # type: ignore
        self.buttonBox.rejected.connect(Summary.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Summary)

    def retranslateUi(self, Summary):
        _translate = QtCore.QCoreApplication.translate
        Summary.setWindowTitle(_translate("Summary", "Dialog"))
        self.label_5.setText(_translate("Summary", "Unique Cards Visited"))
        self.label.setText(_translate("Summary", "Questions Correct"))
        self.accuracyLabel.setText(_translate("Summary", "-- %"))
        self.correctLabel.setText(_translate("Summary", "-/-"))
        self.label_3.setText(_translate("Summary", "Accuracy"))
        self.cardsLabel.setText(_translate("Summary", "--"))
        self.label_7.setText(_translate("Summary", "Time Spent"))
        self.timeLabel.setText(_translate("Summary", "--:--:--"))
